package LaaturaporttiApp;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import LaaturaporttiApp.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.17 13:08:02 // Generated by ComTest
 *
 */
public class AutoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi129 */
  @Test
  public void testRekisteroi129() {    // Auto: 129
    Auto auto1 = new Auto(); 
    assertEquals("From: Auto line: 131", 0, auto1.getIdNro()); 
    auto1.rekisteroi(); 
    Auto auto2 = new Auto(); 
    auto2.rekisteroi(); 
    int n1 = auto1.getIdNro(); 
    int n2 = auto2.getIdNro(); 
    assertEquals("From: Auto line: 137", n2 - 1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString181 */
  @Test
  public void testToString181() {    // Auto: 181
    Auto auto = new Auto(); 
    auto.parse("1|        Laitela Ismo|    455006 |ismo.laitela@gmail.com|FRT-555 | 1|2005|24.06.2015|100|100|60|80 |100|100|100|100|100|80|70|40|100 |fiat500.png|Auto kaikenkaikkiaan hyvässä kunnossa."); 
    assertEquals("From: Auto line: 184", true, auto.toString().startsWith("1|Laitela Ismo|455006|ismo.laitela@gmail.com|FRT-555|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse220 */
  @Test
  public void testParse220() {    // Auto: 220
    Auto auto = nre Auto(); 
    auto.parse("1|        Laitela Ismo|    455006 |ismo.laitela@gmail.com|FRT-555 | 1|2005|24.06.2015|100|100|60|80 |100|100|100|100|100|80|70|40|100 |fiat500.png|Auto kaikenkaikkiaan hyvässä kunnossa."); 
    assertEquals("From: Auto line: 223", 1, auto.getIdNro()); 
    assertEquals("From: Auto line: 224", true, auto.toString().startsWith("1|Laitela Ismo|455006|")); 
    auto.rekisteroi(); 
    int n = auto.getIdNro(); 
    auto.parse(""+(n+20)); 
    auto.rekisteroi(); 
    assertEquals("From: Auto line: 230", n+20+1, auto.getIdNro()); 
  } // Generated by ComTest END
}